CAPABILITY_RISK_TIERS: dict[str, int] = {
    "fs.read": 0,
    "search.read": 0,
    "git.status": 0,
    "skill.catalog.lookup": 0,
    "mcp.resource.read": 0,
    "a2a.agent.discover": 0,
    "fs.write.workspace": 1,
    "exec.shell.sandboxed": 1,
    "test.run": 1,
    "git.commit": 1,
    "exec.shell.network": 2,
    "mcp.tool.invoke": 2,
    "git.push": 3,
    "a2a.agent.call": 3,
    "deploy.staging": 3,
    "db.write": 3,
    "browser.submit.external": 3,
    "deploy.prod": 4,
    "db.drop": 4,
}
