"""Install manifest tracking for generated files."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path


@dataclass(frozen=True)
class ManifestEntry:
    """A single tracked file or directory in the install manifest."""

    path: str
    entry_type: str  # "file" or "directory"
    created_by: str  # e.g. "init", "update", "platform"
    created_at: str  # ISO timestamp
    checksum: str | None = None  # SHA-256 of file at creation time


class InstallManifest:
    """Tracks all files generated by Reins for clean uninstall."""

    MANIFEST_FILE = ".reins/.install-manifest.json"

    def __init__(self, repo_root: Path) -> None:
        self._repo_root = repo_root
        self._entries: list[ManifestEntry] = []

    @property
    def repo_root(self) -> Path:
        return self._repo_root

    def load(self) -> None:
        """Read manifest from disk if it exists."""
        manifest_path = self._repo_root / self.MANIFEST_FILE
        if not manifest_path.exists():
            self._entries = []
            return
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        self._entries = [ManifestEntry(**entry) for entry in data.get("entries", [])]

    def save(self) -> None:
        """Write manifest to disk as JSON."""
        manifest_path = self._repo_root / self.MANIFEST_FILE
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        data = {"entries": [asdict(e) for e in self._entries]}
        manifest_path.write_text(
            json.dumps(data, indent=2) + "\n", encoding="utf-8"
        )

    def record_file(self, path: Path, created_by: str) -> None:
        """Add a file entry with its SHA-256 checksum."""
        rel_path = str(path.relative_to(self._repo_root))
        checksum = self._compute_checksum(path)
        entry = ManifestEntry(
            path=rel_path,
            entry_type="file",
            created_by=created_by,
            created_at=datetime.now(timezone.utc).isoformat(),
            checksum=checksum,
        )
        self._entries.append(entry)

    def record_directory(self, path: Path, created_by: str) -> None:
        """Add a directory entry."""
        rel_path = str(path.relative_to(self._repo_root))
        entry = ManifestEntry(
            path=rel_path,
            entry_type="directory",
            created_by=created_by,
            created_at=datetime.now(timezone.utc).isoformat(),
            checksum=None,
        )
        self._entries.append(entry)

    def get_entries(self) -> list[ManifestEntry]:
        """Return all manifest entries."""
        return list(self._entries)

    def get_files(self) -> list[ManifestEntry]:
        """Return only file entries."""
        return [e for e in self._entries if e.entry_type == "file"]

    def get_directories(self) -> list[ManifestEntry]:
        """Return directory entries sorted deepest-first for safe removal."""
        dirs = [e for e in self._entries if e.entry_type == "directory"]
        return sorted(dirs, key=lambda e: e.path.count("/"), reverse=True)

    def is_tracked(self, path: Path) -> bool:
        """Return True if path is tracked in the manifest."""
        rel_path = str(path.relative_to(self._repo_root))
        return any(e.path == rel_path for e in self._entries)

    def is_modified(self, entry: ManifestEntry) -> bool:
        """Return True if file checksum differs from recorded value."""
        if entry.checksum is None:
            return False
        abs_path = self._repo_root / entry.path
        if not abs_path.exists():
            return False
        current_checksum = self._compute_checksum(abs_path)
        return current_checksum != entry.checksum

    @staticmethod
    def _compute_checksum(path: Path) -> str | None:
        """Compute SHA-256 checksum of a file."""
        if not path.is_file():
            return None
        hasher = hashlib.sha256()
        hasher.update(path.read_bytes())
        return hasher.hexdigest()
